config/routes.rb
Rails.application.routes.draw do
    devise_for :users
    # TopicsController
	resources :topics, only: [:index, :new, :create, :show] do
		# StatesController
		resources :states, only: [:show]
	end
	post "/topics/:topic_id/states/:id" => "states#create"

    #Homecontroller
	root to: 'home#top'
	get "terms" => "home#terms"
    # get "/usage" => "home#usage"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def top
        if user_signed_in?
            redirect_to topics_path
        end
    end
    def terms

    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/terms.html.erb
<div class="home_wrapper">
    <div class="top_wrapper">
        <div class="centering_container pt-3em">
        	<h1>利用規約</h1>
			<div class="mb-10px">
				<p>本規約は、インターネットサイト「ろんばと(https://ronbato.com)」の利用条件を定めるものとします。</p>
				<p>利用者は、本規約の内容を十分に理解した上でその内容を遵守することに同意して本サービスを利用するものとし、本サービスを利用した場合には、当該利用者は本規約を遵守することに同意したものとみなします。</p>
			</div>

			<h2>基本事項</h2>
			<p>以下の基本的なことをお守りください。</p>
			<div class="mb-10px mt-10px">
				<p>他の人を不愉快にさせることは投稿しないでください。</p>
				<p>ルールとマナーをまもって利用してください。</p>
				<p>犯罪行為や迷惑行為はおやめください。問題のある投稿があった場合、法的措置を取らせていただく可能性があります。</p>
				<p>本サービスの利用を通じて問題が発生した場合、本サービス運営者は一切の責任を負わないこととします。</p>
				<p>本サービスの利用は全て、サービス利用者の自己責任となります。</p>
			</div>

			<% if false %>
			<h2>サービス内容</h2>
			<div class="mb-10px">
				<p>本サービス利用者（以下「ユーザー」といいます。）はサイト内の規定のフォームから主張の投稿を投稿できます。</p>
			</div>

			<h2>責任の所在</h2>
			<div class="mb-10px">
				<p>ユーザーは、本サービスの利用に関して発生する責任が全てユーザーに帰すことを承諾します。</p>
				<p>ユーザーは、話題と無関係な広告の投稿に関して、相応の費用を支払うことを承諾します</p>
				<p>ユーザーは、投稿された内容及びこれに含まれる知的財産権、著作権やその他の権利につき、本サービス運営者に対し、無償で譲渡することを承諾します。</p>
				<p>ユーザーは、本サービス運営者あるいはその指定する者に対して、著作者人格権を一切行使しないことを承諾します。</p>
			</div>

			<h2>運営者の権利</h2>
			<div class="mb-10px">
				<p>本サービス運営者は、ユーザーが行った投稿の削除、改変などを含むあらゆる権利を有しているものとします。また、これらはユーザーの同意なしに行えるものとし、これに対しユーザーは異議を申し立てることはできないこととします。</p>
				<p>本サービス運営者は、ユーザーの削除、登録情報の変更をユーザーの同意なく行えるものとします。これに対しユーザーは異議を申し立てることはできないこととします。</p>
				<p>本サービス運営者は、本サービスの内容の変更、サービスの停止、終了を自由に行えるものとします。</p>
			</div>

			<h2>規約の変更</h2>
			<div class="mb-10px">
				<p>本規約はユーザーの同意なく変更することができます。規約の変更は本サイトへの掲載をもって施行されるものとします。</p>
			</div>
			<% end %>

			<p>令和4年5月7日 制定・施行</p>
        </div>
    </div>
</div>

app/views/home/top.html.erb
<div class="home_wrapper">
    <div class="top_wrapper">
        <div class="top_message">
            <h1>さあ、討論をしよう</h1>
            <p class="about">ろんばとはオンラインでディベートができるサイトです。</p>

            <div class="btn_wrapper">
                <%= link_to("アカウント作成", new_registration_path(resource_name), class: "btn account positon_center") %>
                <%= link_to("ログイン", new_session_path(resource_name), class: "btn login positon_center") %>
            </div>

            <div class="lets_start">
                <%= link_to("今すぐ始める＞", "/topics") %>
            </div>
        </div>
        <main>

        </main>
    </div>
</div>